### ISSUE TITLE
显示停止运行

### ISSUE THREAD

**Issue by feng-jerry** [PKUNoRun/PKUNoRunHelper#1]
<img width="510" alt="屏幕快照 2020-10-30 18 55 04" src="https://user-images.githubusercontent.com/73300370/97697266-ba454e00-1ae1-11eb-900c-f29cbf753ea5.png">
解析页面可以正常显示姓名学号，并输入距离、配速。但点击“播放”按钮后，就停止运行了。请问可能是哪里出了问题呢？

**Comment by HamiltonHuaji** [comment]
按理说在应用崩溃的时候会弹出错误日志，你能提供日志截图吗？（类似下图
![Screenshot_20201031_200233](https://user-images.githubusercontent.com/39890671/97778819-c77f3d00-1bb4-11eb-8371-6456751e78e4.png)
）
或者根本没有弹出错误日志就崩溃了？
